import Head from 'next/head'
import { ReactElement } from 'react'

export default function Home(): ReactElement {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Contacts</h1>
      </main>

      <footer>footer</footer>
    </div>
  )
}
